### ISSUE TITLE
WARN  - Failed to parse URL - java.lang.IllegalArgumentException: Malformed escape pair

### ISSUE THREAD

**Issue by TheZappa** [RakambdaOrg/ChannelPointsMiner#600]
### Description

Hi Rakambda,

First of all I want to thank you for all the hard work you put in this project. 
I have been using it for a long time, ever since you made your fork from the inspired python project and then when you started making your own application.

Today I updated from version 2.2.2 to the lastest main version 2.2.7 and I wanted to report a warning that I get a lot in the logs. So not necessarily a bug, but I didn't know where I could post this to inform you, so up front excuses if this is the wrong place to let you know about it.

It is very minor and I wanted to ask if it is something on my end that is the problem or not. 
Looking at it it is purely URL parsing problem.

I will place my logger to not log warnings anymore for the time being.

If you need more information let me know!

I run it on raspberry pi 4 in linux using openjdk.

Best regards and keep up the good work :)

### Version / commit

2.2.7

### Relevant log output

```shell
023-09-29T14:57:45,288 WARN  - Failed to parse URL: https://static-cdn.jtvnw.net/jtv_user_pictures/7084c2b9-16f3-4653-bfd3-b14cf9c05932-profile_image-%s.png
java.lang.IllegalArgumentException: Malformed escape pair at index 98: https://static-cdn.jtvnw.net/jtv_user_pictures/7084c2b9-16f3-4653-bfd3-b14cf9c05932-profile_image-%s.png
	at java.net.URI.create(URI.java:906) ~[?:?]
	at fr.rakambda.channelpointsminer.miner.util.json.URLDeserializer.deserialize(URLDeserializer.java:37) [miner-shaded.jar:?]
	at fr.rakambda.channelpointsminer.miner.util.json.URLDeserializer.deserialize(URLDeserializer.java:16) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3755) [miner-shaded.jar:?]
	at fr.rakambda.channelpointsminer.miner.util.json.JacksonUtils.read(JacksonUtils.java:60) [miner-shaded.jar:?]
	at fr.rakambda.channelpointsminer.miner.api.ws.data.response.MessageData.setMessage(MessageData.java:32) [miner-shaded.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) [miner-shaded.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3755) [miner-shaded.jar:?]
	at fr.rakambda.channelpointsminer.miner.util.json.JacksonUtils.read(JacksonUtils.java:60) [miner-shaded.jar:?]
	at fr.rakambda.channelpointsminer.miner.api.ws.TwitchPubSubWebSocketClient.onMessage(TwitchPubSubWebSocketClient.java:74) [miner-shaded.jar:?]
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) [miner-shaded.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986) [miner-shaded.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910) [miner-shaded.jar:?]
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402) [miner-shaded.jar:?]
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234) [miner-shaded.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) [miner-shaded.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 98: https://static-cdn.jtvnw.net/jtv_user_pictures/7084c2b9-16f3-4653-bfd3-b14cf9c05932-profile_image-%s.png
	at java.net.URI$Parser.fail(URI.java:2976) ~[?:?]
	at java.net.URI$Parser.scanEscape(URI.java:3104) ~[?:?]
	at java.net.URI$Parser.scan(URI.java:3127) ~[?:?]
	at java.net.URI$Parser.checkChars(URI.java:3145) ~[?:?]
	at java.net.URI$Parser.parseHierarchical(URI.java:3229) ~[?:?]
	at java.net.URI$Parser.parse(URI.java:3177) ~[?:?]
	at java.net.URI.<init>(URI.java:623) ~[?:?]
	at java.net.URI.create(URI.java:904) ~[?:?]
	... 46 more
```

**Comment by couchoud-t** [comment]
Yep I'm aware of it, the "%s" at the end isn't a valid URL. Though I agree this is annoying to have these errors all the time.
I'll probably will change the field from being an URL to a simple String (so that it doesn't check that the URL is valid).

I'll keep this issue open to track it.

**Comment by TheZappa** [comment]
Thanks for the fast reply and solution, appriciate it :)
